#!/bin/bash
# Scaffold a new skill folder + a registry stub. registry.json is the single source
# of truth; framework/skills/INDEX.md and the routing manifest are generated by
# build-index.sh. Usage: add-skill.sh <skill-name>

set -e

SKILL_NAME="$1"
if [ -z "$SKILL_NAME" ]; then
  echo "Usage: add-skill.sh <skill-name>"
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
SKILL_DIR="$REPO_ROOT/framework/skills/$SKILL_NAME"
REGISTRY="$REPO_ROOT/framework/skills/registry.json"
TODAY="$(date +%Y-%m-%d)"

if [ -d "$SKILL_DIR" ]; then
  echo "Skill '$SKILL_NAME' already exists at $SKILL_DIR"
  exit 1
fi

mkdir -p "$SKILL_DIR/scripts"

cat > "$SKILL_DIR/SKILL.md" << EOF
---
name: $SKILL_NAME
model: sonnet
description: >
  TODO: Write a description that specifies when this skill should trigger.
  Be explicit about trigger phrases and contexts. If in doubt, the agent
  should load this skill.
version: 1.0.0
author: <your-name>
protected: false
dependencies: []
last_updated: $TODAY
---

# $(echo "$SKILL_NAME" | tr '[:lower:]' '[:upper:]') Skill

## Quick Reference

| Task | Approach |
|------|----------|
| TODO | TODO |

---

## Critical Rules

TODO: List the things that cause failures if ignored.

---

## Sub-References

| File | When to load |
|------|-------------|
| TODO | TODO |

---

## Dependencies

\`\`\`bash
# TODO: List install commands
\`\`\`
EOF

cat > "$SKILL_DIR/scripts/README.md" << EOF
# $SKILL_NAME Scripts

Executable utilities for this skill. Document expected scripts here.
EOF

# Add a registry stub (single source of truth). INDEX.md is generated, not hand-written.
python3 - "$REGISTRY" "$SKILL_NAME" "$TODAY" << 'PYEOF'
import sys, json
registry_path, name, date = sys.argv[1:]
with open(registry_path) as f:
    registry = json.load(f)
if name not in registry["skills"]:
    registry["skills"][name] = {
        "path": f"framework/skills/{name}/SKILL.md",
        "source": "local",
        "version": "1.0.0",
        "installed": date,
        "model": "sonnet",
        "needs": "TODO",
        "description": "TODO",
        "triggers": []
    }
    with open(registry_path, "w") as f:
        json.dump(registry, f, indent=2)
    print("Registry stub added.")
PYEOF

# Regenerate INDEX.md + routing manifest from the registry.
bash "$REPO_ROOT/framework/agent/scripts/build-index.sh"

echo ""
echo "✓ Skill '$SKILL_NAME' scaffolded at framework/skills/$SKILL_NAME"
echo ""
echo "Next steps:"
echo "  1. Fill in SKILL.md content"
echo "  2. Complete the registry entry (model, needs, description, triggers) in framework/skills/registry.json"
echo "  3. Re-run: bash framework/agent/scripts/build-index.sh"
echo "  4. Commit: git add framework/skills/$SKILL_NAME framework/skills/registry.json framework/skills/INDEX.md personal/agent/"
