#!/bin/bash
# Rebuild all agent indexes in one pass.
# Run after adding/editing any topic file, skill, or framework route.
# Usage: bash framework/agent/scripts/build-index.sh

REPO_ROOT="$(git worktree list --porcelain | awk '/^worktree/{sub(/^worktree /,""); print; exit}')"
TOPICS_DIR="$REPO_ROOT/personal/knowledge/topics"
TOPICS_INDEX="$REPO_ROOT/personal/agent/topics-index.json"
KNOWLEDGE_INDEX="$REPO_ROOT/personal/knowledge/INDEX.md"
CATEGORIES_PATH="$REPO_ROOT/framework/knowledge/topic-categories.json"
MANIFEST="$REPO_ROOT/personal/agent/routing-manifest.json"
FRAMEWORK_ROUTES="$REPO_ROOT/personal/agent/framework-routes.json"
REGISTRY="$REPO_ROOT/framework/skills/registry.json"
PERSONAL_REGISTRY="$REPO_ROOT/personal/skills/registry.json"

python3 - "$TOPICS_DIR" "$TOPICS_INDEX" "$KNOWLEDGE_INDEX" "$CATEGORIES_PATH" "$MANIFEST" "$FRAMEWORK_ROUTES" "$REGISTRY" "$PERSONAL_REGISTRY" << 'PYEOF'
import sys, os, re, json
from datetime import date

topics_dir             = sys.argv[1]
topics_out             = sys.argv[2]
knowledge_index_out    = sys.argv[3]
categories_path        = sys.argv[4]
manifest_out           = sys.argv[5]
framework_routes_path  = sys.argv[6]
registry_path          = sys.argv[7]
personal_registry_path = sys.argv[8]

def load_categories():
    if not os.path.exists(categories_path):
        return {}
    with open(categories_path, encoding="utf-8") as f:
        return json.load(f).get("categories", {})

categories = load_categories()

def infer_category(fname):
    base = fname.replace(".md", "")
    candidates = []
    for slug, meta in categories.items():
        for prefix in meta.get("prefixes", []):
            if base.startswith(prefix) or base == prefix:
                candidates.append((len(prefix), slug))
    if not candidates:
        return None
    candidates.sort(reverse=True)
    return candidates[0][1]

# ── 1. Build topics-index ──────────────────────────────────────────────────
topics = {}

def iter_topic_files(root):
    for dirpath, _, filenames in os.walk(root):
        for fname in sorted(filenames):
            if fname.endswith(".md"):
                full = os.path.join(dirpath, fname)
                rel = os.path.relpath(full, root).replace("\\", "/")
                yield rel

for rel_path in iter_topic_files(topics_dir):
    fname = os.path.basename(rel_path)
    path = os.path.join(topics_dir, rel_path)
    with open(path, encoding="utf-8") as f:
        raw = f.read()

    status  = "unknown"
    updated = None
    m = re.search(r'> status:\s*(\w[\w-]*)', raw)
    if m: status = m.group(1)
    m = re.search(r'updated:\s*(\d{4}-\d{2}-\d{2})', raw)
    if m: updated = m.group(1)
    if not updated:
        m = re.search(r'Last refreshed:\s*(\d{4}-\d{2}-\d{2})', raw)
        if m: updated = m.group(1)

    title = fname.replace(".md", "")
    m = re.search(r'^#\s+(.+)', raw, re.MULTILINE)
    if m: title = m.group(1).strip()

    tags = []
    m = re.search(r'\*\*Tags\*\*:\s*(.+)', raw)
    if m: tags = [t.strip() for t in m.group(1).split(",")]

    category = None
    m = re.search(r'\*\*Category\*\*:\s*(\S+)', raw)
    if m:
        category = m.group(1).strip()
    if not category:
        category = infer_category(fname)
    folder = os.path.dirname(rel_path)
    if folder and folder != "." and not category:
        category = folder
    elif folder and folder != "." and category and category != folder:
        print(f"  WARN: category/folder mismatch: {rel_path} (category={category}, folder={folder})")

    summary = ""
    in_header = True
    skip_prefixes = ("**Tags**", "**Category**", "**Related topics**")
    for line in raw.splitlines():
        if in_header and (line.startswith(">") or line.startswith("#") or not line.strip()):
            continue
        in_header = False
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or stripped.startswith("|") or stripped.startswith("-"):
            continue
        if any(stripped.startswith(p) for p in skip_prefixes):
            continue
        summary = stripped[:120]
        break

    key = fname.replace(".md", "")
    topics[key] = {
        "path": "personal/knowledge/topics/" + rel_path,
        "title": title,
        "status": status,
        "updated": updated,
        "category": category,
        "folder": folder if folder != "." else "",
        "tags": tags,
        "summary": summary
    }

with open(topics_out, "w", encoding="utf-8") as f:
    json.dump({"topics": topics}, f, indent=2)
print(f"topics-index: {len(topics)} topics")

# ── 1b. Generate personal/knowledge/INDEX.md by category ───────────────────
grouped = {}
for key, topic in topics.items():
    if topic["status"] == "archived":
        continue
    cat = topic.get("category") or "uncategorized"
    grouped.setdefault(cat, []).append((key, topic))

index_lines = [
    "# Personal Knowledge Index",
    "",
    "Generated by `build-index.sh` — **do not edit by hand**.",
    "Browse by category; use `bash framework/agent/scripts/list-topics.sh --category <slug>` for CLI.",
    "",
    f"**Topics**: {sum(len(v) for v in grouped.values())} active across {len(grouped)} categories",
    "",
]
for cat in sorted(grouped.keys(), key=lambda c: (c == "uncategorized", categories.get(c, {}).get("label", c))):
    meta = categories.get(cat, {})
    label = meta.get("label", cat.replace("-", " ").title())
    desc = meta.get("description", "")
    index_lines += [f"## {label}", ""]
    if desc:
        index_lines.append(f"{desc}")
        index_lines.append("")
    for key, topic in sorted(grouped[cat], key=lambda x: x[0]):
        title = topic.get("title", key)
        updated = topic.get("updated") or "—"
        summary = topic.get("summary", "")
        folder = topic.get("folder", "")
        loc = f"{folder}/" if folder else ""
        index_lines.append(f"- **`{loc}{key}.md`** — {title} _(updated {updated})_")
        if summary:
            index_lines.append(f"  - {summary[:100]}")
    index_lines.append("")

os.makedirs(os.path.dirname(knowledge_index_out), exist_ok=True)
with open(knowledge_index_out, "w", encoding="utf-8") as f:
    f.write("\n".join(index_lines))
print(f"personal knowledge INDEX.md: {len(grouped)} categories")

# ── 2. Build routing-manifest ──────────────────────────────────────────────
routes = []

# 2a. Framework routes (static)
with open(framework_routes_path, encoding="utf-8") as f:
    fw = json.load(f)
routes.extend(fw["routes"])

# 2b. Framework skills
framework_skills = {}
if os.path.exists(registry_path):
    with open(registry_path, encoding="utf-8") as f:
        framework_registry = json.load(f)
    framework_skills = framework_registry.get("skills", {})
    for name, meta in framework_skills.items():
        triggers = meta.get("triggers", [name])
        routes.append({
            "triggers": triggers,
            "load": meta["path"],
            "also": [],
            "type": "skill",
            "skill_type": "framework",
            "description": meta.get("description", "")
        })

# 2c. Personal skills
personal_skills = {}
if os.path.exists(personal_registry_path):
    with open(personal_registry_path, encoding="utf-8") as f:
        personal_registry = json.load(f)
    personal_skills = personal_registry.get("skills", {})
    for name, meta in personal_skills.items():
        triggers = meta.get("triggers", [name])
        routes.append({
            "triggers": triggers,
            "load": meta["path"],
            "also": [],
            "type": "skill",
            "skill_type": "personal",
            "description": meta.get("description", "")
        })

# 2d. Topics (from topics-index, active only)
for key, topic in topics.items():
    if topic["status"] == "archived":
        continue
    triggers = [key.replace("-", " "), key]
    triggers += topic.get("tags", [])
    cat = topic.get("category")
    if cat:
        triggers.append(cat)
        triggers.append(cat.replace("-", " "))
        cat_meta = categories.get(cat, {})
        triggers.append(cat_meta.get("label", cat))
        triggers += cat_meta.get("aliases", [])
    # add keywords from title words (lowercased, >3 chars)
    title_words = [w.lower() for w in re.findall(r'\b\w{4,}\b', topic["title"])]
    triggers += title_words
    # deduplicate preserving order
    seen = set()
    unique = []
    for t in triggers:
        if t and t not in seen:
            seen.add(t)
            unique.append(t)
    routes.append({
        "triggers": unique,
        "load": topic["path"],
        "also": [],
        "type": "topic",
        "updated": topic["updated"]
    })

manifest = {
    "generated": date.today().isoformat(),
    "routes": routes
}

with open(manifest_out, "w", encoding="utf-8") as f:
    json.dump(manifest, f, indent=2)
print(f"routing-manifest: {len(routes)} routes ({len(topics)} topics, {len(framework_skills)} framework skills, {len(personal_skills)} personal skills, {len(fw['routes'])} framework routes)")

# ── 3. Generate framework INDEX.md ────────────────────────────────────────
# registry.json is the single source of truth. Sub-refs are auto-discovered from
# each skill dir so they never drift. Never hand-edit INDEX.md.
skills_dir = os.path.dirname(registry_path)
index_out  = os.path.join(skills_dir, "INDEX.md")
lines = [
    "# Skills Index — Fast Lookup",
    "",
    "Generated from `framework/skills/registry.json` by `build-index.sh` — **do not edit by hand**.",
    "Authoring guide: `framework/knowledge/skill-authoring.md`",
    "",
]
for name, meta in sorted(framework_skills.items()):
    skill_path = meta.get("path", "")
    sub = []
    sd = os.path.join(skills_dir, name)
    if os.path.isdir(sd):
        sub = sorted(f for f in os.listdir(sd) if f.endswith(".md") and f != "SKILL.md")
    lines += ["---", "", f"## {name}", f"**Path**: `{skill_path}`"]
    if meta.get("model"):
        lines.append(f"**Model**: {meta['model']}")
    lines.append("**Triggers**: " + ", ".join(meta.get("triggers", [])))
    lines.append(f"**Does**: {meta.get('description','')}")
    if meta.get("needs"):
        lines.append(f"**Needs**: {meta['needs']}")
    if sub:
        lines.append("**Sub-refs**: " + " · ".join(sub))
    lines.append(f"**Last updated**: {meta.get('updated', meta.get('installed','—'))}")
    lines.append("")

with open(index_out, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print(f"framework skills INDEX.md: {len(framework_skills)} skills")

# ── 4. Generate personal INDEX.md ─────────────────────────────────────────
personal_skills_dir = os.path.dirname(personal_registry_path)
personal_index_out  = os.path.join(personal_skills_dir, "INDEX.md")
lines = [
    "# Personal Skills Index",
    "",
    "Generated from `personal/skills/registry.json` by `build-index.sh` — **do not edit by hand**.",
    "",
]
for name, meta in sorted(personal_skills.items()):
    skill_path = meta.get("path", "")
    sub = []
    sd = os.path.join(personal_skills_dir, name)
    if os.path.isdir(sd):
        sub = sorted(f for f in os.listdir(sd) if f.endswith(".md") and f != "SKILL.md")
    lines += ["---", "", f"## {name}", f"**Path**: `{skill_path}`"]
    if meta.get("model"):
        lines.append(f"**Model**: {meta['model']}")
    lines.append("**Triggers**: " + ", ".join(meta.get("triggers", [])))
    lines.append(f"**Does**: {meta.get('description','')}")
    if meta.get("needs"):
        lines.append(f"**Needs**: {meta['needs']}")
    if sub:
        lines.append("**Sub-refs**: " + " · ".join(sub))
    lines.append(f"**Last updated**: {meta.get('updated', meta.get('installed','—'))}")
    lines.append("")

if os.path.exists(personal_skills_dir):
    with open(personal_index_out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"personal skills INDEX.md: {len(personal_skills)} skills")
PYEOF
